### ISSUE TITLE
ImportError: No module named rnn_enhancement

### ISSUE THREAD

**Issue by anantzoid** [nicolas-ivanov/tf_seq2seq_chatbot#13]
It seems `_get_predicted_sentence` is still using `rnn_enhancement.decoding_enhanced`'s  `sample_with_temperature`.

Will be happy to submit a PR pushing that function to `seq2seq_model_utils.py`.

**Comment by nicolas-ivanov** [comment]
@anantzoid thank you for the suggestion,
however `sample_with_temperature` used to work in a wrong way (tokens sampling should be done on every step of decoding process, not post factum) so I completely removed it. See the latest commit with the updated prediction function.
