### ISSUE TITLE
update Seq2Seq_Upgrade_TensorFlow requirements to 0.6.0 (currently at 0.5.0)

### ISSUE THREAD

**Issue by kinoc** [nicolas-ivanov/tf_seq2seq_chatbot#2]
Just a request to update the requirements of Seq2Seq_Upgrade_TensorFlow to match the local requirement for tensorflow==0.6.0 , it is currently at 0.5.0

**Comment by nicolas-ivanov** [comment]
@kinoc sure, I'll update the requirements, but first I have to check that all the functionaly (multiGPU support, for example) works with tensorflow==0.6.0

**Comment by ghyun** [comment]
+1 on this, would like compatibility with tensorflow==0.7.1

**Comment by sevazhidkov** [comment]
+1

**Comment by nicolas-ivanov** [comment]
Updated to tensorflow 0.9.0.
